# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build app and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install
    - name: Build Next.js app
      run: yarn build
    - name: Run tests
      run: yarn test
    - name: Run Cypress test suite
      uses: cypress-io/github-action@v2
      with:
        browser: chrome
        start: yarn start
        # record: true # - use this to record the tests (Cypress.io account needed)
        # more info: https://github.com/marketplace/actions/cypress-io#record-test-results-on-cypress-dashboard
        
      
    

